SELECT * from customer limit 5

--Q1. what is the total revenue generated by male vs female customer?
select gender, sum(purchase_amount) as revenue
from customer group by gender

--Q2. which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'yes' and purchase_amount <= (select AVG(purchase_amount)from customer)

--Q3. which are the top 5 products with highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating)desc
limit 5;

--Q4. Compare the average purchase amount between standard and express shipping?
select shipping_type,
round(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. do subscribed customers spend more? compare average spend and total revenue bw subscribed and non?
select subscription_status,
COUNT(customer_id) as total_customers,
round(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;